# Generated by Django 3.2.2 on 2021-05-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('date_of_receipt', models.DateField(verbose_name='Дата приёма на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего выплачено')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.employeemodel')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
